name: LIKWID Build Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-x86-accessdaemon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make accessdaemon
      run: make ACCESSMODE=accessdaemon BUILD_SYSFEATURES=true -j

  build-x86-perfevent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make perf_event
      run: make ACCESSMODE=perf_event BUILD_SYSFEATURES=true -j
  build-aarch64-perfevent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v3
      name: make perf_event
      with:
        arch: aarch64
        distro: ubuntu_latest
        githubToken: ${{ github.token }}
        install: |
          apt update
          apt upgrade -y
          apt install -y build-essential
        run: |
          make COMPILER=GCCARM ACCESSMODE=perf_event BUILD_SYSFEATURES=true -j
